blog/urls.py
import sys
import os

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# print BASE_DIR
# sys.path.append(BASE_DIR)
# reload(sys)
from django.conf.urls import url
from django.contrib import admin
import blog.views as bv


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^index/$', bv.index),
    url(r'^article/(?P<article_id>[0-9]+)$', bv.article_page,name='article_page'),
    url(r'^edit/$', bv.edit_papge,name='edit_page'),
    url(r'^edit/action/$', bv.edit_action,name='edit_action'),

]

myblog/urls.py
import sys
import os

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# print BASE_DIR
# sys.path.append(BASE_DIR)
# reload(sys)
from django.conf.urls import url,include
from django.contrib import admin
import blog.views as bv


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^index/', bv.index),
    # url(r'^blog/', include('blog.urls')),
    url(r'^blog/', include('blog.urls',namespace='blog')),


]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32,default='title')
    content = models.TextField(null=True) # 允许为空

    def __unicode__(self):
        return self.title

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.shortcuts import render
import models

# Create your views here.


# def index(request):
#     return HttpResponse('HELLO word')

# def index(request):
#     return render(request,'blog/index.html',{'hello':'hello blog'})


# def index(request):
#     article = models.Article.objects.get(pk=1)
#     return render(request,'blog/index.html',{'article':article})   # 给前端传递对象


def index(request):
    articles = models.Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})   # 给前端传递对象

def article_page(request,article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_page.html',{'article':article})

def edit_papge(request):

    return render(request,'blog/edit_page.html')

def edit_action(request):
    title = request.POST.get('title','TITLE')
    content = request.POST.get('content','CONTENT')
    models.Article.objects.create(title=title,content=content)
    articles = models.Article.objects.all()
    return render(request,'blog/index.html',{'article':articles})

blog/templates/blog/article_page.html
<!DOCTYPE html><html lang="en"><head>    <meta charset="UTF-8">    <title>Article Page</title></head><br><h1>{{ article.title }}</h1><br/><h3>{{ article.content }}</h3><br/><br/><a href="">修改文章</a></body></html>

blog/templates/blog/edit_page.html
<!DOCTYPE html><html lang="en"><head>    <meta charset="UTF-8">    <title>Edit Page</title></head><body><form action="{% url 'blog:edit_action' %}" method="post">{#    <% csrf_token %>#}    <label>文章标题            <input type="text" name="title"/>    </label><br/>    <label>文章内容            <input type="text" name="content"/>    </label>    <br/>    <input type="submit" name="提交"/></form></body></html>

blog/templates/blog/index.html
<!DOCTYPE html><html lang="en"><head>    <meta charset="UTF-8">    <title></title></head><body><a>    <h1><a href="">文章列表</a></h1></a>{% for article in articles %}    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a><br/>{%endfor %}</body></html>